package investigatorManager;

public enum DepartmentType {
    POLICE_INVESTIGATION_TERRITORIAL,
    POLICE_INQUIRI,
    POLICE_INVESTIGATION_DISTRICT,
    POLICE_INVESTIGATION_MAIN_DEPARTMENT,
    INVESIGATE_COMITEE

}
